---
- name: Wait 10 minutes for standard deployment to finish
  pause:
    minutes: 10

- name: Verify server is up and accepting connections
  local_action: wait_for host={{ hostname }} state=started delay=30 timeout=900 port=22
  become: false
